services:
  - type: web
    name: kzmedia
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        fromDatabase:
          name: kzmedia-db
          property: connectionString
databases:
  - name: kzmedia-db
    plan: free
